### ISSUE TITLE
Activity List

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#1]
## Value Proposition

As a user,
I want to browse a list of activities,
so that I can easily find and explore new activities that interest me.

## Description

<img width="744" alt="ActivityList" src="https://github.com/user-attachments/assets/65bf6962-8ee6-49cc-b8b1-cd6f3604494c">

## Acceptance Criteria

- [ ] The homepage displays a list of activities.
- [ ] The activities list is headlined with its purpose
- [ ] Each activity listing includes:
- [ ] Activity title
- [ ] Activity image
- [ ] Activity categories
- [ ] The list supports vertical scrolling to accommodate multiple entries

## Tasks

- [ ] Create feature branch feature/activities-list
- [ ] Inspect and adapt the example data in the assets folder
- [ ] Add an imageUrl for each activity, for example from unsplash.com
- [ ] Create ActivitiesList component
- [ ] Import data from assets folder
- [ ] Create an ActivityCardPreview
- [ ] use map method to create a list of ActivityCardPreviews inside ActivityList
