### ISSUE TITLE
Add Global Styling 

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#17]
## Value proposition
As a user
I want to experience good and simple design
In order to navigate easily around the App and have a good experience doing so.
## Acceptance criteria
- [ ] Global styling should define the unanimously used colors 
- [ ] Buttons with functionality should have the same styling features
- [ ] Layout (Header and Navigation) should be updated in styling
## Tasks
- [ ] create a new branch feature/styling
- [ ] in styles.js add the selected colors (var -- hexcode)
- [ ] add the chosen fonts to use
- [ ] also add uniform styles for buttons or cards, such as padding, border-radius, gaps, margins.
- [ ] create a separate file for styled components, which are used in multiple places
- [ ] add icons for filter, edit and delete option as SVGs

**Comment by Roland-Hufnagel** [comment]
If you don't add a wireframe or text to the description please remove the template:
Scribble / design or text
Precise, no unnecessary information
