### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#18]
## Value proposition
As a user
I want to be able to upload a picture to my newly created activity
In order to give other users a preview of what the activity is like.
## Acceptance criteria
- [ ] When clicking  the Image-button the user can select a picture from their local device
 - [ ] Upload should accept all image formats (image/*)
## Tasks
- [ ]  Create feature/Image-upload branch
- [ ] Use Cloudinary for storage.
- [ ] Setting up the project via Web Capstone Docs.
- [ ] https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary
   -  Create a "ImageUpload" component
    -  Create a handleSubmit function and get its data.
    -  Create an API Route (e.g. /pages/api/upload/index.js).
    - Write a handler function to send our image file to Cloudinary.
- [ ] Replace URL of default picture Input field with a new Upload Button in the "Form" component

**Comment by eduskx** [comment]
looks good! some improvements: 

- write "user can selecet a picture from **their** local device"
- which image formats are accepted?
