### ISSUE TITLE
Add Responsiveness

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#19]
## Value proposition
As a user
I want to be able to have good user experience in the App, but also on the Browser.
In order to have access to the application from which ever device I am currently using.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] Content of the pages should be easily usable on every device or screen
- [ ] the display in the App on the phone has a navbar on the bottom which is always displayed
- [ ] on the browser the navigation is placed on the top left or right on the page and is visible (open) when clicked
- [ ] in the browser version hover functionality is included
- [ ] also the activity cards should be designed using grid to have a better overview
## Tasks
- [ ] create branch feature/responsiveness
- [ ] add media queries to secure certain behavior or looks according to the screen size

**Comment by eduskx** [comment]
looks good! perhaps add some wireframes :)
