### ISSUE TITLE
Activity details

### ISSUE THREAD

**Issue by thaliyil** [thaliyil/capstone_trailBlazer#2]
## Value proposition

As a user

I want to access detailed information about each activity,

so that I can make informed decisions and plan my activities effectively.

## Description

![Image](https://github.com/user-attachments/assets/916cd6d3-9521-491c-8bfe-a25ae3791ca8)

## Acceptance criteria

- [ ] Each activity in the activities list has a link to a details page.
- [ ] Each details page contains:
  - [ ] Activity title
  - [ ] Activity image
  - [ ] Activity description
  - [ ] Activity categories
  - [ ] Activity area
  - [ ] Activity country
- [ ] The detailed view includes a "back" link, allowing users to easily navigate back to the list of activities.

## Tasks

- [ ] Create feature branch feature/activity-details
- [ ] Create Component ActivityDetails 
- [ ] ActivityDetails props: id, title, image, description, categories, area ,country
- [ ] Create the page pages/activities-details/[id] that renders ActivityDetails
- [ ] Read the query parameter id from next/router
- [ ] Use the id to find the activity to display using find method
- [ ] Create Link Component in ActivityList to navigate to details page 
- [ ] Adjust the Layout on details page (wireframe)
