### ISSUE TITLE
Spotlight Page

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#20]
## Value proposition
As a user
I want to have suggested random activities,
In order to be inspired and discover new activities, even if I don't know what to look for.
## Acceptance criteria
- [ ] There should be separate page with a randomly selected activity
- [ ] The user can easily navigate to the Spotlight page via Navbar
- [ ] Heading should tell user they are on SpotlightPage
## Tasks
- [ ] Create a new branch feature/spotlight-page
- [ ] Create a component SpotlightPage which displays a random activity
- [ ] Add  (Link) 'Spotlight' to the Navbar that navigates to SpotlightPage
- [ ] Use math.random to get a random activity

**Comment by stekug** [comment]
Looks good! It would be nice to have some wire frames / some pictures or layout/design ideas to get a better understanding of how it should look like!
