### ISSUE TITLE
Select mode for countries

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#21]
## Value proposition
As a user
I want to be able to select a country from a dropdown menu when creating or editing an activity.
In order to prevent spelling mistakes und make my experience easier.
## Acceptance criteria
- [ ] Instead of an input field, there should be a dropdown menu displayed in the ActivityForm
- [ ] When clicking the dropdown menu there is a list of the countries of the world to select from.
## Tasks
- [ ] Create a new branch feature/countries-select
- [ ] In the ActivityForm component replace the input field for 'country' with a select input
- [ ] Add the countriesData either in a separate file in 'assets' / or fetch the data from an API
- [ ] use the map method to display every country as an option in select
