### ISSUE TITLE
Weather forecast

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#22]
## Value proposition
As an outdoor enthusiast
I want to have a weather forecast displayed for each activity.
In order to see if the weather is suitable for my outdoor experience
## Description
 - [ ] In DetailsPage underneath the picture of the selected image, there should be a weather forecast for the current day
 - [ ] Some kind of visuals (icons or emojis) should replicate the forecast weather (e.g. sun, rain, wind)
## Acceptance criteria
- [ ] Current weather forecast for the day is displayed in DetailsPage
- [ ] The forecast is updated, when weather changes
- [ ] Forecast is dependent on the location of the activity
## Tasks
- [ ] Create branch feature/forecast
- [ ] Find suitable free weather API
- [ ] Fetch data with async function from API
- [ ] Display the wanted data in separate section underneath the image
- [ ] If needed, add icons or emojis suiting the current weather

**Comment by SylvieDoumet** [comment]
Add a wireframe to your US to visualize the icons you want to implement / display you want to achieve
