### ISSUE TITLE
Create notes option

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#23]
## Value proposition
As a user
I want to write notes on the Details Page
In order to remember my ideas
## Acceptance criteria
- [ ]  Text should be displayed at the end of the Details Page
- [ ]  Notes can be edited directly on the detailspage.
## Tasks
- [ ] Create "feature/activity-notes" branch
 - [ ] Create a useState for Notes.
- [ ]  Create a "Notes" component
 - [ ]    Textarea with default content "Notes..."
     Edit button
- [ ]  Write an  Edit function.
 - [ ] Insert new "notes"  inside the Activity array
- [ ]  Render "Notes" component on Details Page.
