### ISSUE TITLE
Book mark activity

### ISSUE THREAD

**Issue by thaliyil** [thaliyil/capstone_trailBlazer#3]
## Value proposition

As a user

I want to mark activities as favourites,

so that I can quickly access and track the ones I am most interested in.

## Description

![Image](https://github.com/user-attachments/assets/ae2a48e1-b331-4cd8-9452-03a57baaeb04)

## Acceptance criteria

- [ ] Each listed activity includes a bookmark option.
- [ ] Clicking the bookmark button of an unbookmarked activity adds it to the bookmarked list.
- [ ] Clicking the bookmark button of a bookmarked activity removes it from the bookmarked list.
- [ ] The bookmarked activities are displayed on a separate list accessible via a new page dedicated to bookmarked activities.
- [ ] There is a clearly visible link on the homepage to navigate to the bookmarked activities page.
- [ ] There is a clearly visible link on the bookmarked activities page to navigate back to the homepage.
- [ ] Bookmarked activities are visually highlighted by a distinct bookmark icon colour to differentiate them from unbookmarked activities.
- [ ] If there are no bookmarked activities in the bookmarked list, a message is displayed to the user indicating that there are no bookmarks.

## Tasks

- [ ] Create feature branch feature/bookmark-activity
- [ ] Create an additional state activitiesInfo to save further information for ActivityDetails
- [ ] Make the activitiesInfo state globally available for all pages
- [ ] Store the bookmark flag (true/false) in the activitiesInfo
- [ ] Create the component BookmarkButton
- [ ] BookmarkButton props: isBookmarked, onToggleBookmarked
- [ ] Render the BookmarkButton component in ActivityCardPreview and ActivityDetails
- [ ] Create the page pages/bookmarks that renders a list of the bookmarked activities
- [ ] Use data from the activitiesInfo state to filter for all bookmarked activities
- [ ] Pass the list of all bookmarked activities via prop activities to the ActivityList component
