### ISSUE TITLE
Code Improvements

### ISSUE THREAD

**Issue by RebeccaPavelt** [thaliyil/capstone_trailBlazer#31]
## Value proposition
As a user
I want to have a good experience on the application.
In order to use it regularly.
## Acceptance criteria
- [ ] Code should be readable and understandable
- [ ] Naming should be fitting 
- [ ] Fix style adjustments
## Tasks
- [ ] Create branch feature/clean-code
- [ ] Go through every file, delete unnecessary spaces and lines
- [ ] Rename elements if needed
- [ ] Make sure styling is consistent
