### ISSUE TITLE
Create activity

### ISSUE THREAD

**Issue by thaliyil** [thaliyil/capstone_trailBlazer#4]
## Value proposition

As a user
 I want to create and save my own personal activities,
In order to easily access and manage them for future use.

## Description

<img width="872" alt="Bildschirmfoto 2024-07-29 um 18 40 05" src="https://github.com/user-attachments/assets/f83fb28a-f039-4e1f-8847-e3c24c37aeb6">

## Acceptance criteria

- [ ] A form for adding an activity is displayed at the top of the homepage.
- [ ] The form must include labelled fields for: 
   - Activity title
   - Activity description
   - Activity categories (dynamic form fields)
  -  Activity area
    - Activity country
- [ ] The form is headlined with its purpose.
- [ ] The following fields are mandatory:
   - Activity title
    - Activity categories (dynamic form fields)
- [ ] The category is selected via a dropdown menu with the following options: Outdoor, Sport, Water, Nature, Adventure, Winter.
- [ ] The categories dropdown must include a default option, "Please select a category", and necessitates a selection.
- [ ] Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- [ ] Upon form submission, the new activity is added to the top of the activities list.

## Tasks

- [ ] Create feature branch feature/create-activity
- [ ] The category options are listed in the [categories.json](https://github.com/neuefische/hh-web-24-5/blob/main/capstone/activity-planner/assets/categories.json) file
- [ ] Create a Form component with props handleAddActivity
- [ ] Create a state and save it in local storage
- [ ] import uid to generate  a new id for newly added activity
