### ISSUE TITLE
Delete activity

### ISSUE THREAD

**Issue by thaliyil** [thaliyil/capstone_trailBlazer#5]
## Value proposition
As a user
I want to be able to delete activities that are no longer relevant,
so that I can maintain a clean and organised activities list, ensuring it’s always up to date.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria

- [ ]     Each activity details view includes an easily accessible delete option.
 - [ ]    Clicking the delete option triggers a confirmation dialog.
 - [ ]    The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
 - [ ]    The dialog includes options for both confirming the deletion and cancelling the action.
 - [ ]    The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- [ ]     Upon confirming the deletion, the user is immediately redirected to the overview of all activities, and the activity is removed from the list.
- [ ]     If all activities are deleted, a message appears indicating that there are no activities and providing an option to add new ones.

## Tasks
- [ ] Create feature branch feature/delete-activity
- [ ] Create a delete button for each activity with props onDeleteActivity
- [ ] Implement a confirmation dialogue in the handleDeleteActivity
- [ ] use find method to identify the activity to be removed
- [ ] use router.push to redirect to activity list page after confirmation from user
- [ ]   If activity list is empty,display a message and the Form component
