### ISSUE TITLE
Update activity

### ISSUE THREAD

**Issue by thaliyil** [thaliyil/capstone_trailBlazer#7]
## Value proposition
As a user
I want to update the details of existing activities,
so that they reflect the most accurate and relevant information.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] Each activity details page includes an easily accessible edit option.
- [ ] Clicking the edit option opens a new page with a form pre-filled with the activity's existing details for modification.
- [ ] The form allows for edits to all activity details, including: 
   - Activity title
   - Activity description
   -  Activity categories (dynamic form fields)
  -   Activity area
   -  Activity country
 - [ ] The following fields are mandatory:
    - Activity title
    - Activity categories (dynamic form fields)
- [ ]  The form section includes options for both saving and cancelling the action.
- [ ] The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- [ ] Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- [ ] Upon confirming the save, the user is immediately redirected to the details page of the edited activity, and the changes are saved and reflected.
## Tasks
- [ ] Create feature branch feature/update-activity
- [ ] Create an edit button in ActivityDetails page that navigates to pages/activities/[id]/edit
- [ ] Import data  from asset folder (activities.json)
- [ ] use useRouter to find the id of the actvity to be edited 
- [ ]  Find id from activities  that matches id from query
- [ ] Create an  EditActivity component that renders a Form component  with two buttons   save and cancel
- [ ]  Clicking cancel button redirects to details page (previous page:router.back)
 - [ ]   when clicking on save  button,the particular object should be updated
